### PR TITLE
Add support for user-specified filters

### PR DESCRIPTION
**Pull request by bfhealy**
This PR adds support for user-specified filters as a new environment variable to pass to the analysis slurm script.

### CODE REVIEW

**Comment by Theodlz** [comment]
Hi @bfhealy. Super cool! Didnt know it was this straightforward with NMMA.

I was thinking about the skyportal side of things, however. Aside from the UI, it could be Skyportal that skips the filters before sending them to the service. Might reduce ingress/egress. Also, we want to filter on instruments as well, which only skyportal can do super quickly. So maybe its better to just do it there and not here? What do you think? Also wondering what @mcoughlin thinks.

**Comment by mcoughlin** [comment]
@bfhealy @Theodlz I think if it's easy to do in SP, good to do there. If that will take time, nothing wrong with getting it done this way.

**Comment by bfhealy** [comment]
@Theodlz @mcoughlin Currently the user will need to specify comma-separated filters in a new UI box specific to NMMA analyses (with a default "all", see the screenshot below). I very much like the idea of having SkyPortal select filters (and instruments) for any analysis without requiring this new specific input. Perhaps this could be implemented as a couple new dropdowns just below "Share data with". That may take some additional time for me to figure out, though.

Screen Shot 2023-12-06 at 2 50 02 PM

**Comment by Theodlz** [comment]
@bfhealy I actually have a PR to write with the analysis, fixing some UI stuff. Let me just take care of it!

**Comment by bfhealy** [comment]
Sounds good, thanks @Theodlz!

**Comment by bfhealy** [comment]
This will be addressed at the SkyPortal level (see https://github.com/skyportal/skyportal/pull/4669)

**Pull request closed without merging**
