### PR TITLE
Use sncosmo-generic prior for all sncosmo models

### PR DESCRIPTION
**Pull request by bfhealy**
This PR adds a `PRIOR` variable to `expanse.py` that either takes the name of `MODEL` or becomes `"sncosmo-generic"` if the model is one of the `sncosmo` names. 

`sncosmo` is added as a requirement.

### CODE REVIEW

**Review by Theodlz — APPROVED** [review]
LGTM!

**Comment by bfhealy** [comment]
@Theodlz Great, thanks! Will this change deploy to heroku automatically when I merge?

**Comment by Theodlz** [comment]
@bfhealy it should yes! Let me merge it now and see if that worked

**Comment by Theodlz** [comment]
yep it worked! I manually asked for a new deploy thinking it didn't, but as soon as the CI turned to green another deploy job triggered 👍

**Pull request merged**
